# Generated by Django 6.0.3 on 2026-03-06 05:35

import django.db.models.deletion
import festival.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del festival')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='España', max_length=100, verbose_name='País')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('tematica', models.CharField(max_length=200, verbose_name='Temática')),
                ('aforo_maximo', models.PositiveIntegerField(verbose_name='Aforo máximo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='festivales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Festival',
                'verbose_name_plural': 'Festivales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('director', models.CharField(max_length=150, verbose_name='Director/a')),
                ('anio', models.IntegerField(validators=[festival.models.validar_anio], verbose_name='Año de estreno')),
                ('duracion_minutos', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('genero', models.CharField(choices=[('drama', 'Drama'), ('comedia', 'Comedia'), ('terror', 'Terror'), ('ciencia_ficcion', 'Ciencia Ficción'), ('documental', 'Documental'), ('animacion', 'Animación'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('accion', 'Acción'), ('fantasia', 'Fantasía')], max_length=30, verbose_name='Género')),
                ('sinopsis', models.TextField(max_length=1000, verbose_name='Sinopsis')),
                ('puntuacion', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[festival.models.validar_puntuacion], verbose_name='Puntuación (0-10)')),
                ('poster_url', models.URLField(blank=True, verbose_name='URL del póster')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peliculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-anio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('sala', models.CharField(choices=[('sala_principal', 'Sala Principal'), ('sala_a', 'Sala A'), ('sala_b', 'Sala B'), ('sala_c', 'Sala C'), ('auditorio', 'Auditorio'), ('al_aire_libre', 'Al aire libre')], max_length=30, verbose_name='Sala')),
                ('entradas_disponibles', models.PositiveIntegerField(verbose_name='Entradas disponibles')),
                ('precio_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Precio de entrada (€)')),
                ('es_preestreno', models.BooleanField(default=False, verbose_name='Es preestreno')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='festival.festival', verbose_name='Festival')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='festival.pelicula', verbose_name='Película')),
            ],
            options={
                'verbose_name': 'Proyección',
                'verbose_name_plural': 'Proyecciones',
                'ordering': ['fecha_hora'],
                'unique_together': {('festival', 'sala', 'fecha_hora')},
            },
        ),
    ]
